name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.24.0'

    - name: Build
      run: |
        make
      env:
        GOARCH: arm
        GOARM: v7

    - name: gosec
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec ./...

    - name: Archive stuff
      uses: actions/upload-artifact@v4.0.0
      with:
        name: build-artefacts
        path: |
          listenbrainz-prometheus-bridge
